language: node_js
node_js:
- "lts/*"
before_script:
- npm install -g gulp
- npm install
script: gulp && gulp prepublish
deploy:
  provider: npm
  email: injan0913@gmail.com
  api_key:
    secure: QoEWGlb937JojC3SMGsv4Jc9MlJGgNd36FgSRf9Gjet+OSTvwuY0ly7qvPpuYbdxbGOtgRHNLoUQeb3TpL2TnoyWW1phJxyEAFbZZT2qdMeoAYVKCB/h93PPLkh9ajVcEvyQw0MZwRZThWabI515dwwxROqS+asjMVgL+V4wBHvD9qBekBiuF3PCet5ZJLu+0FjiKUkNUfoyDR74IowgIEvwKlTX4cXeOZ5e3GCejmTAPAHuEBh64DkPPILlnQvX6Qj3L9yVsD5GnV1ktKrKek66CenGdxwjGmW8C4Oa7zpTJON2/u+Dt0J3qCpqNXDjF/Ncl3qmAjqamuatw+sShEx3bDBld+YzvOpd3aA4LS2gng73ZQIplXyky4ACxdIzb7H/qWXvHNLe+PM9wMUWFkJMfvZLbjUdfAgAYkZx6IPQ5AlQYyKPzkNo9E7TDVHJA9Xm5rcTp1BdzT1ayDaJ4gRcTPvS0BHLFK8gATZMWDVjjvSSHLy7qvTzR/1uSr02fkPjO4V4dXHR0JWcr5BUMAv5PHL3EOYHk0RkY5Vwf5EgsZqv3aSxBBM9y4u1O5+ZnIZqN5aAxpyRZRueCDItK9/XuhBmN4TqqQcPTuMrKSf5Br9/hcvDZO7LP99QP5C8qRPyIgew8VGvvEnJcDoxFNboRH2jgD/X6tfVp1laE5Q=
  on:
    tags: true
    branch: master
  skip_cleanup: true
